name: covid19_spread
dependencies:
  - python=3.7
  - pytorch=1.4.0
  - matplotlib=3.0.3
  - ccache
  - h5py
  - jupyter
  - nbconvert
  - networkx
  - numpy
  - pandas
  - pip
  - pylint
  - scipy
  - scikit-learn
  - seaborn
  - tqdm
  - click
  - pip:
    - bokeh==2.0.2
    - pyyaml
    - sqlalchemy
    - submitit
    - tick
    - tensorboardX
    - pre-commit
    - black==19.10b0
    - pytest
    - nb2mail
    - bs4
    - dropbox
    - slackclient
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - hdx-python-api
    - covidcast
