name: covid19_spread
dependencies:
  - python=3.7
  - pytorch=1.4.0
  - matplotlib=3.0.3
  - ccache
  - h5py
  - jupyter
  - nbconvert
  - networkx
  - numpy
  - pandas
  - pip
  - pylint
  - scipy
  - scikit-learn
  - seaborn
  - tqdm
  - click
  - pip:
    - bokeh
    - pyyaml
    - sqlalchemy
    - submitit
    - tick
    - tensorboardX
    - pre-commit
    - black==19.10b0
    - pytest
