name: covid19_spread
dependencies:
  - python=3.7
  - pytorch
  - cudatoolkit
  - matplotlib=3.0.3
  - h5py
  - jupyter
  - nbconvert
  - numpy
  - pandas
  - pip
  - pylint
  - rtree
  - scipy
  - scikit-learn
  - seaborn
  - tqdm
  - click
  - pip:
    - bokeh==2.0.2
    - pyyaml
    - submitit
    - tensorboardX
    - pre-commit
    - black==19.10b0
    - pytest
    - dropbox
    - slackclient
    - google-api-python-client
    - google-auth-httplib2
    - google-auth-oauthlib
    - hdx-python-api
    - covidcast
    - torchcontrib
    - pygithub
    - zoltpy
    - pykwalify
    - pymmwr
