name: covid19_spread
dependencies:
  - python=3.7
  - pytorch=1.3.1
  - matplotlib=3.0.3
  - ccache
  - h5py
  - jupyter
  - nbconvert
  - networkx
  - numpy
  - pandas
  - pylint
  - scipy
  - scikit-learn
  - seaborn
  - tqdm
  - pip:
    - bokeh
    - tick
    - tensorboardX
