region: at
population: &fpop data/austria/population.csv
validation:
  days: &vdays 7
  output: validation-at.csv
forecast:
  output: forecast-at.csv
prediction_interval_:
  nsamples: 10
  output_mean: at_mean.csv
  output_std: at_std.csv
metasir:
  data: data/austria/data.csv
  output: metasir_model.bin
  train:
    fpop: *fpop
    decay: rbf
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: lsq
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false    
ar:
  output: ar_model.bin
  data: data/austria/data.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 5
    timeout: 15
  #preprocess:
  #  smooth: 7
  train:
    fpop: *fpop
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_1]
    window: [15, 20, 25]
    momentum: [0.9]
    lr: [0.001]
    weight_decay: [0.1, 0.2]
    temp_smoothing: [0]
    niters: 20000
    loss: nb
    t0: 5
    test_on: *vdays
