region: at
population: &fpop data/austria/population.csv
notebooks:
  cv:
    - notebooks/Austria.ipynb
    - "notebooks/Model Analysis.ipynb"
validation:
  days: 7
  output: validation.csv
forecast:
  output: forecast.csv
  days: &fdays 7
prediction_interval:
  nsamples: 1000
  intervals: [0.99, 0.95, 0.8]
  output: piv.csv
bar:
  output: bar_model.bin
  data: data/austria/data.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 360
  #preprocess:
  #  smooth: 5
  train:
    time_features:
      -
        - data/austria/fb/mobility_features.pt
        - data/austria/google/mobility_features_google.pt
        - data/austria/symptom-survey/smoothed_cli.pt
        - data/austria/symptom-survey/smoothed_mc.pt
        - data/austria/symptom-survey/smoothed_dc.pt
        - data/austria/weather/weather_features.pt
    fpop: *fpop
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_2]
    window: [5, 10, 15]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.2, 0.3]
    niters: [30000]
    granger: [0.5]
    temporal: [100]
    eta: [0.002, 0.02, 0.2]
    loss: nb
    t0: 0
    test_on: *fdays
