region: es
population: &fpop covid19_spread/data/population-data/spain-region-population.csv
basegraph: &fgraph covid19_spread/data/spain/state_graph.pt
validation:
  days: &vdays 21
  output: validation.csv
forecast:
  output: forecast.csv
prediction_interval:
  nsamples: 1000
  intervals: [0.99, 0.95]
  output: piv.csv
bar:
  output: bar_model.bin
  data: covid19_spread/data/spain/data_cases.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    n_models: 1
    fpop: *fpop
    # features: covid19_spread/data/usa/county_features.pt
    time_features_:
      -
        - covid19_spread/data/spain/shifted_features_province.pt
    time_features:
      -
        - covid19_spread/data/spain/fb/mobility_features_fb.pt
        - covid19_spread/data/spain/google/mobility_features_google.pt
        - covid19_spread/data/spain/symptom_survey/smoothed_cli.pt
        - covid19_spread/data/spain/symptom_survey/smoothed_mc.pt
        - covid19_spread/data/spain/symptom_survey/smoothed_dc.pt
        # - covid19_spread/data/spain/testing/total_features.pt
        - covid19_spread/data/spain/weather/weather_features.pt
    # graph: *fgraph
    no_cross_correlation: False
    activation: sigmoid
    decay: [lstm2_2]
    window: [14, 21, 28]
    dropout: [0.1, 0.2]
    lr: [0.005]
    momentum: [0.9]
    # weight_decay: [0.2]
    weight_decay: [0.1, 0.2]
    niters: [30000]
    temporal: [10]
    granger: 0.5
    eta: [0.002, 0.02, 0.2]
    loss: nb
    t0: 0
    test_on: *vdays
