region: it
population: &fpop covid19_spread/data/italy/population.csv
validation:
  days: 14
  output: validation.csv
forecast:
  output: forecast.csv
  days: &fdays 14
prediction_interval:
  nsamples: 1000
  intervals: [0.99, 0.95, 0.8]
  output: piv.csv
bar:
  output: bar_model.bin
  data: covid19_spread/data/italy/data-upc.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 360
  # preprocess:
  #   smooth: 5
  train:
    fpop: *fpop
    activation: sigmoid
    decay: [latent2_2]
    window: [20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.1, 0.2]
    # niters: [30000]
    niters: [20000]
    granger: [0.5]
    # granger: [0.3, 0.4, 0.5]
    temporal: [0.5, 1, 2]
    eta: [0.1, 0.2, 0.3]
    loss: nb
    t0: 5
    test_on: *fdays
