region: new-jersey
population: &fpop data/population-data/US-states/new-jersey-population.csv
validation:
  days: &vdays 14
  output: validation-nj.csv
forecast:
  output: forecast-nj.csv
metasir:
  output: metasir_model.bin
  data: data/new-jersey/timeseries.h5
  train:
    fpop: *fpop
    decay: latent
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: lsq
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false    
ar:
  data: data/new-jersey/timeseries.h5
  output: ar_model.bin
  train:
    fpop: *fpop
    decay: powerlaw
    window: 1
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false
sir:
  data: data/new-jersey/timeseries.h5
  output: sir_model.npy
  train:
    fpop: *fpop
    window: [1, 3, 5, 10, 14, 20]
    recovery_days: [10, 12, 14]
    distancing_reduction: [0.1, 0.2, 0.5, 0.8, 0.9]
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
mhp:
  data: data/new-jersey/timeseries.h5
  output: mhp_model.bin
  resources:
    gpus: 1
  simulate:
    trials: 10
    max_events: 2000000
    days: *vdays
  train:
    dim: [10, 15, 20]
    base_intensity: [True, False]
    alpha_scale: [-10, -15]
    const_beta: [8, 10, 15]
    weight_decay: [0]
    max_events: [1000000]
    maxcor: [100]
    optim: lbfgs
    max_events: 500000
    epochs: 200
    sparse_grads: False
