region: new-jersey
data: &fdat data/new-jersey/timeseries.h5
population: &fpop data/population-data/US-states/new-jersey-population.csv
validation:
  input: &fvdata timeseries_filtered.h5
  output: validation.csv
  days: &vdays 7
metrics:
  output: metrics.csv
metasir:
  module: metasir
  output: metasir_model.bin
  train:
    fdat: *fvdata
    fpop: *fpop
    decay: latent
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: lsq
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false    
ar:
  module: ar
  output: ar_model.bin
  train:
    fdat: *fvdata
    fpop: *fpop
    decay: powerlaw
    window: 3
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
    
