region: new-jersey
population: &fpop data/population-data/US-states/new-jersey-population.csv
validation_days: &vdays 7
metasir:
  output: metasir_model.bin
  data: data/new-jersey/timeseries.h5
  train:
    fpop: *fpop
    decay: latent
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: lsq
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false    
ar:
  data: data/new-jersey/timeseries.h5
  output: ar_model.bin
  train:
    fpop: *fpop
    decay: powerlaw
    window: 1
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false
sir:
  data: data/new-jersey/timeseries.h5
  output: sir_model.npy
  train:
    fpop: *fpop
    window: 14
    recovery_days: 14
    distancing_reduction: 0.2
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays

    
