region: new-jersey
population: &fpop data/population-data/US-states/new-jersey-population.csv
validation:
  days: &vdays 7
  output: validation-nj.csv
forecast:
  output: forecast-nj.csv
backfill:
  - 2020-04-12
  - 2020-04-13
  - 2020-04-15
  - 2020-04-19
  - 2020-04-20
  - 2020-04-22
  - 2020-04-26
  - 2020-04-27
  - 2020-04-29
  - 2020-04-30
  - 2020-05-01
  - 2020-05-03
  - 2020-05-04
  - 2020-05-06   
ar:
  data: data/new-jersey/data_cases.csv
  output: ar_model.bin
  preprocess: 
    smooth: [1, 3]
  resources:
    gpus: 1
    memgb: 10
  train:
    fpop: *fpop
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_1]
    window: [5, 10, 15]
    lr: [0.005, 0.01]
    momentum: [0.9]
    weight_decay: [0.1, 0.2]
    niters: [20000]
    temp_smoothing: 0
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  data: data/new-jersey/timeseries.h5
  output: sir_model.npy
  train:
    fpop: *fpop
    window: 20
    recovery_days: 10
    distancing_reduction: 0.8
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays