region: ny

population: &fpop data/population-data/US-states/new-york-population.csv
validation_days: &vdays 7
ar:
  data: data/nystate/data-new.csv
  output: ar_model.bin
  train:
    fpop: *fpop
    decay: powerlaw
    window: 1
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  train:
    fdat: *fvdata
    fpop: *fpop
    window: 14
    recovery_days: 14
    distancing_reduction: 0.2
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays

    
