region: ny
population: &fpop data/population-data/US-states/new-york-population.csv
validation:
  days: &vdays 14
  output: validation-ny.csv
forecast:
  output: forecast-ny.csv
ar:
  data: data/nystate/data-new.csv
  output: ar_model.bin
  resources:
    gpus: 1
    cpus: 1
    memgb: 10
    timeout: 30
  train:
    fpop: *fpop
    decay: [latent2_1, latent4_1, latent8_1, latent16_1]
    window: [1, 5, 10, 15, 20]
    lr: [0.001, 0.005, 0.01]
    momentum: [0.9, 0.99]
    weight_decay: 0
    niters: 40000
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  data: data/nystate/timeseries.h5
  train:
    fpop: *fpop
    window: [1, 3, 5, 10, 14, 20]
    recovery_days: [10, 12, 14]
    distancing_reduction: [0.05, 0.1, 0.2, 0.5, 0.8, 0.9, 1.0]
    days: 8
    # number of days to keep for forecast
    keep: *vdays
