region: nystate
population: &fpop data/population-data/US-states/new-york-population.csv
notebooks:
  backfill:
    - notebooks/NY.ipynb
    - "notebooks/Model Analysis.ipynb"
  cv:
    - "notebooks/Model Analysis.ipynb"
validation:
  days: 21
  output: validation.csv
forecast:
  output: forecast.csv
  days: &fdays 21
backfill:
  # LANL
  #- 2020-04-05
  #- 2020-04-08
  #- 2020-04-12
  # - 2020-04-15
  - 2020-04-19
  - 2020-04-22
  - 2020-04-26
  - 2020-05-03
  - 2020-05-06
  - 2020-05-10
  - 2020-05-17
  - 2020-05-24
  - 2020-05-31
  - 2020-06-07
  - 2020-06-13
  - 2020-06-21
  - 2020-06-28
  - 2020-07-05
  - 2020-07-12
  - 2020-07-19
  - 2020-07-26
  - 2020-08-02
  - 2020-08-09
ar:
  data: data/nystate/data_cases.csv
  output: ar_model.bin
  #preprocess: 
  #  smooth: [1, 3, 5]
  resources:
    gpus: 1
    cpus: 1
    memgb: 10
    timeout: 30
  train:
    fpop: *fpop
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_2]
    window: [15, 20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.1, 0.2]
    niters: [30000]
    temp_smoothing: 0
    loss: nb
    t0: 0
    test_on: *fdays
sir:
  module: sir
  output: sir_model.npy
  data: data/nystate/data-new.csv
  train:
    fpop: *fpop
    window: 1
    recovery_days: 10
    distancing_reduction: 0.8
    days: *fdays
    # number of days to keep for forecast
    keep: *fdays
mhp:
  data: data/nystate/timeseries.h5
  output: mhp_model.bin
  resources:
    gpus: 1
  simulate:
    trials: 10
    max_events: 2000000
    days: *fdays
  train:
    dim: [10, 15, 20]
    base_intensity: [True, False]
    alpha_scale: [-10, -15]
    const_beta: [8, 10, 15]
    weight_decay: [0]
    max_events: [1000000]
    maxcor: [100]
    optim: lbfgs
    max_events: 500000
    epochs: 200
    sparse_grads: False
bar:
  output: bar_model.bin
  data: data/usa/data_cases_ny.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    n_models: 1
    fpop: *fpop
    # features: [[data/usa/county_features.pt]]
    self_correlation: True
    time_features:
      -
         - data/usa/testing/ratio_features.pt
         - data/usa/testing/total_features.pt
         - data/usa/fb/mobility_features.pt
         - data/usa/google/mobility_features.pt
         - data/usa/google/weather_features.pt
         - data/usa/symptom-survey/features_state.pt
         - data/usa/symptom-survey/features_county.pt
    activation: sigmoid
    decay: [lstm2_2]
    # decay: attn
    # decay: [wave1_4_2_3, wave1_4_2_5]
    # decay: [conv14_3]
    # window: [14, 21]
    window: [7, 14, 21, 28]
    lr: [0.001]
    # lr: [0.05]
    momentum: [0.9]
    dropout: [0.1]
    #weight_decay: [0.2, 0.3]
    weight_decay: [0.1, 0.2]
    #niters: [30000]
    niters: [25000]
    granger: [0.5]
    #temporal: [0.1, 1]
    temporal: [100, 1000]
    eta: [0.1, 0.2]
    # eta: [0.3, 0.4, 0.5]
    loss: nb
    t0: 0
    test_on: *fdays
diffsir:
  output: dsir_model.bin
  data: data/usa/data_cases_ny.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    fpop: data/usa/population.csv
    time_features:
       -
         #- data/usa/testing/features.pt
         - data/usa/fb/mobility_features.pt
         - data/usa/symptom-survey/features.pt
         - data/usa/google/mobility_features.pt
    decay: [latent32_1]
    niters: [20000]
    dropout: 0
    weight_decay: 0
    lr: [0.001]
    momentum: 0.9
    loss: nb
    min_count: 1
    t0: 0
    test_on: *fdays
codec:
  output: codec_model.bin
  data: data/usa/data_cases_ny.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    time_features:
    #  -
    #    - data/usa/testing/features.pt
    #    - data/usa/fb/mobility_features.pt
       -
         - data/usa/testing/features.pt
         - data/usa/fb/mobility_features.pt
         - data/usa/symptom-survey/features_state.pt
         - data/usa/symptom-survey/features_county.pt
         - data/usa/google/mobility_features.pt
         - data/usa/google/weather_features.pt
    adjoint: False
    dim: [2, 4]
    layers: [2, 4, 6]
    method: euler
    niters: [30000]
    lr: [0.001]
    momentum: 0.9
    weight_decay: [0.4, 0.6, 0.8]
    kinetic: [0]
    loss: nb
    t0: 0
    test_on: *fdays
