region: nystate
population: &fpop covid19_spread/data/population-data/US-states/new-york-population.csv
validation:
  days: 21
  output: validation.csv
forecast:
  output: forecast.csv
  days: &fdays 21
prediction_interval:
  output_mean: mean.csv
  output_std: std.csv
  intervals: [0.99, 0.95, 0.8]
  nsamples: 500
  batch_size: 10
sir:
  module: sir
  output: sir_model.npy
  data: covid19_spread/data/usa/data_cases_ny.csv
  train:
    fpop: *fpop
    window: 1
    recovery_days: 10
    distancing_reduction: 0.8
    days: *fdays
    # number of days to keep for forecast
    keep: *fdays
bar:
  output: bar_model.bin
  data: covid19_spread/data/usa/data_cases_ny.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    n_models: 1
    fpop: *fpop
    # features: [[data/usa/county_features.pt]]
    self_correlation: True
    time_features:
      -
        - covid19_spread/data/usa/testing/total_features_county.pt
        - covid19_spread/data/usa/fb/mobility_features_county_fb.pt
        - covid19_spread/data/usa/fb/mobility_features_county_state_fb.pt
        - covid19_spread/data/usa/google/mobility_features_county_google.pt
        - covid19_spread/data/usa/google/mobility_features_county_state_google.pt
        - covid19_spread/data/usa/google/weather_features_county.pt
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_hh_cmnty_cli-county_state.pt
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_wcli-county_state.pt
        - covid19_spread/data/usa/symptom_survey/doctor-visits_smoothed_adj_cli-county.pt
    activation: sigmoid
    decay: [lstm2_2]
    #window: [20, 25]
    window: [14, 21, 28]
    lr: [0.001]
    momentum: [0.99]
    dropout: [0.1]
    weight_decay: [0.1, 0.2]
    niters: [25000]
    granger: [0.5]
    temporal: [2]
    eta: [0.1, 0.2]
    loss: nb
    t0: 0
    n_models: 5
    test_on: *fdays
    n_models: 5