region: nystate
population: &fpop covid19_spread/data/population-data/US-states/new-york-population.csv
validation:
  days: 7
  output: validation.csv
forecast:
  output: forecast.csv
  days: &fdays 21
sir:
  module: sir
  output: sir_model.npy
  data: covid19_spread/data/usa/data_cases_ny.csv
  train:
    fpop: *fpop
    window: 1
    recovery_days: 10
    distancing_reduction: 0.8
    days: *fdays
    # number of days to keep for forecast
    keep: *fdays
bar:
  output: bar_model.bin
  data: covid19_spread/data/usa/data_cases_ny.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    fpop: *fpop
    # features: covid19_spread/data/usa/county_features.pt
    # time_features:
    #  -
    #    - covid19_spread/data/usa/google/mobility_features.pt
    #    - covid19_spread/data/usa/fb/mobility_features.pt
    #    - covid19_spread/data/usa/symptom-survey/features.pt
    activation: sigmoid
    decay: [latent2_2]
    # decay: [latent2_2, latent16_2, latent32_2]
    window: [20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.2, 0.3]
    niters: [50000]
    granger: [0.5]
    # granger: [0.3, 0.4, 0.5]
    temporal: [0.5, 1, 2]
    # eta: [0.2, 0.3, 0.4]
    eta: [0.2, 0.3, 0.4, 0.5]
    loss: nb
    t0: 0
    test_on: *fdays
