region: nyc
population: &fpop data/population-data/US-states/new-york-population.csv
validation_days: &vdays 7
ar:
  data: data/nystate/data-nyc.csv
  module: ar
  output: ar_model.bin
  train:
    fpop: *fpop
    decay: powerlaw
    window: 1
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    test_on: *vdays