region: nyc
population: &fpop data/population-data/US-states/new-york-population.csv
validation:
  days: &vdays 7
  output: validation-nyc.csv
forecast:
  output: forecast-nyc.csv
ar:
  data: data/nystate/data-nyc.csv
  module: ar
  output: ar_model.bin
  train:
    fpop: *fpop
    decay: powerlaw
    window: 1
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  data: data/nystate/data-nyc.csv
  train:
    fpop: *fpop
    window: 1
    recovery_days: 10
    distancing_reduction: 0.8
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays