region: nys
population: &fpop data/population-data/US-states/new-york-population.csv
validation_days: &vdays 7
  input: &fvdata timeseries_filtered.h5
  output: validation.csv
  days: &vdays 7
metrics:
  output: metrics.csv
ar:
  output: ar_model.bin
  data: data/nystate/timeseries-nys.h5
  train:
    fpop: *fpop
    decay: powerlaw
    window: 2
    lr: 0.005
    weight_decay: 0
    niters: 20000
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
    
