region: us
population: &fpop data/usa/population.csv
basegraph: &fgraph data/usa/state_graph.pt
validation:
  days: &vdays 21
  output: validation.csv
forecast:
  output: forecast.csv
prediction_interval_:
  nsamples: 10
  output_mean: mean.csv
  output_std: std.csv
backfill:
  # LANL
  #- 2020-04-05
  #- 2020-04-08
  #- 2020-04-12
  # - 2020-04-15
  - 2020-04-19
  # - 2020-04-22
  - 2020-04-26
  #- 2020-04-29
  - 2020-05-03
  # - 2020-05-06
  - 2020-05-10
  - 2020-05-17
  - 2020-05-24
  - 2020-05-31
  - 2020-06-07
  - 2020-06-14
  - 2020-06-21
  - 2020-06-28
  - 2020-07-05
  # IHME
  # - 2020-05-01
  # GLEAM
  #- 2020-04-13
  #- 2020-04-20
  #- 2020-04-27
  #- 2020-05-04
  # MIT
  #- 2020-04-22
  #- 2020-04-27
  #- 2020-04-30
  #- 2020-05-04
metasir:
  data: data/usa/data_cases.csv
  output: metasir_model.bin
  train:
    fpop: *fpop
    decay: exp
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: nb
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false
ar:
  output: ar_model.bin
  data: data/usa/data_deaths.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  #preprocess:
  #  smooth: 5
  train:
    fpop: *fpop
    # features: data/usa/county_features.pt
    # time_features: data/usa/mobility_features.pt
    #time_features: [[data/usa/mobility_features.pt,
    #data/usa/symptom_features.pt, data/usa/policy_features.pt]]
    # graph: *fgraph
    #decay: [latent2_1]
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_1]
    window: [10, 15, 20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.1, 0.2]
    # weight_decay: [0.1, 0.2, 0.3, 0.4, 0.5]
    # weight_decay: [0.01]
    niters: [20000]
    temp_smoothing: 0
    #temp_smoothing: [5, 25, 50, 75]
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: 10
    recovery_days: 10
    distancing_reduction: 0.9
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
seir:
  module: seir
  output: seir_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: [8, 10, 12, 14]
    recovery_days: [8, 10, 12, 14, 16]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    cases_to_infections_scale: [1.0, 2.0, 5.0, 10.0, 15.0, 20.0]
    # rate of progression
    sigma: [0.1, 0.15, 0.2, 0.3, 0.4]
sir_adaptive_beta:
  module: sir_adaptive_beta
  output: sir_adaptive_beta_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    min_window: [5, 10, 20, 30]
    recovery_days: [10, 12, 14]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    # scale confirmed cases to get total infections
    cases_to_infections_scale: [1.0, 5.0, 10.0, 15.0]
    rolling_window: 5
    cap: 100.0
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
matrix:
  output: mc_model.bin
  fpop: *fpop
  data: data/usa/data.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  train:
    decay: exp
    epochs: 40000
    bs: 100000 # 10000
    eps: [0.00001]
    lr: [0.0005]
    momentum: [0.99]
    weight_decay: [0.95]
    fit_on: [14]
    k_avg: [10]
    n_embedding: [250]
    seed: [1]
    t0: [0] #, 10] ######
    test_on: *vdays
bar:
  output: bar_model.bin
  data: data/usa/data_cases.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 5
  train:
    fpop: *fpop
    # features: data/usa/county_features.pt
    # time_features:
    #   -
    #     - data/usa/google/mobility_features.pt
    #     - data/usa/fb/mobility_features.pt
    #     - data/usa/symptom-survey/features.pt
    # graph: *fgraph
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_2]
    window: [20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.2, 0.3]
    niters: [50000]
    granger: [0.5]
    temporal: [0.5, 1, 2]
    eta: [0.2, 0.3, 0.4]
    loss: nb
    t0: 0
    test_on: *vdays
naive:
  module: naive
  output: naive_model.npy
  data: data/usa/data_cases.csv
  train:
    days: *vdays

