region: us
population: &fpop data/usa/population_county.csv
basegraph: &fgraph data/usa/state_graph.pt
notebooks:
  backfill:
    # - notebooks/Backtest US.ipynb
    - "notebooks/Model Analysis.ipynb"
  cv:
    - "notebooks/Model Analysis.ipynb"
validation:
  days: &vdays 21
  output: validation.csv
test:
  days: 60
  output: validation.csv
forecast:
  output: forecast.csv
prediction_interval_:
  nsamples: 10
  output_mean: mean.csv
  output_std: std.csv
backfill_:
  # deaths
  - 2020-05-03
  - 2020-05-18
  - 2020-05-24
  - 2020-06-08
  - 2020-06-14
  - 2020-06-21
  - 2020-06-24
  - 2020-06-29
  - 2020-07-06
  - 2020-07-23
backfill:
  # Google
  #- 2020-05-11
  #- 2020-05-18
  #- 2020-05-25
  #- 2020-05-30
  #- 2020-06-08
  #- 2020-06-20
  #- 2020-06-27
  # COVIDhub
  - 2020-07-05
  - 2020-07-12
  - 2020-07-19
  - 2020-07-26
  - 2020-08-02
  - 2020-08-09
  - 2020-08-16
  - 2020-08-23
  - 2020-08-30
  # LANL
  #- 2020-04-05
  #- 2020-04-08
  #- 2020-04-12
  # - 2020-04-15
  #- 2020-04-19
  # - 2020-04-22
  #- 2020-04-26
  #- 2020-04-29
  #- 2020-05-03
  # - 2020-05-06
  #- 2020-05-10
  #- 2020-05-17
  #- 2020-05-24
  #- 2020-05-31
  #- 2020-06-07
  #- 2020-06-14
  #- 2020-06-21
  #- 2020-06-28
  #- 2020-07-05
  # IHME
  # - 2020-05-01
  # GLEAM
  #- 2020-04-13
  #- 2020-04-20
  #- 2020-04-27
  #- 2020-05-04
  # MIT
  #- 2020-04-22
  #- 2020-04-27
  #- 2020-04-30
  #- 2020-05-04
ar:
  output: ar_model.bin
  data: data/usa/data_deaths.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  #preprocess:
  #  smooth: 5
  train:
    fpop: *fpop
    # features: data/usa/county_features.pt
    # time_features: data/usa/mobility_features.pt
    #time_features: [[data/usa/mobility_features.pt,
    #data/usa/symptom_features.pt, data/usa/policy_features.pt]]
    # graph: *fgraph
    #decay: [latent2_1]
    activation: sigmoid
    no_cross_correlation: false
    decay: [latent2_1]
    window: [10, 15, 20, 25]
    lr: [0.001]
    momentum: [0.99]
    weight_decay: [0.1, 0.2]
    # weight_decay: [0.1, 0.2, 0.3, 0.4, 0.5]
    # weight_decay: [0.01]
    niters: [20000]
    temp_smoothing: 0
    #temp_smoothing: [5, 25, 50, 75]
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: 10
    recovery_days: 10
    distancing_reduction: 0.9
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
seir:
  module: seir
  output: seir_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: [8, 10, 12, 14]
    recovery_days: [8, 10, 12, 14, 16]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    cases_to_infections_scale: [1.0, 2.0, 5.0, 10.0, 15.0, 20.0]
    # rate of progression
    sigma: [0.1, 0.15, 0.2, 0.3, 0.4]
sir_adaptive_beta:
  module: sir_adaptive_beta
  output: sir_adaptive_beta_model.npy
  data: data/usa/data_cases.csv
  train:
    fpop: *fpop
    min_window: [5, 10, 20, 30]
    recovery_days: [10, 12, 14]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    # scale confirmed cases to get total infections
    cases_to_infections_scale: [1.0, 5.0, 10.0, 15.0]
    rolling_window: 5
    cap: 100.0
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
bar:
  output: bar_model.bin
  data: data/usa/data_cases.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    n_models: 1
    fpop: data/usa/population_county.csv
    time_features:
      -
        # - data/usa/testing/ratio_features_county.pt
        - data/usa/testing/total_features_county.pt
        - data/usa/fb/mobility_features_county_fb.pt
        - data/usa/fb/mobility_features_county_state_fb.pt
        - data/usa/google/mobility_features_county_google.pt
        - data/usa/google/mobility_features_county_state_google.pt
        - data/usa/google/weather_features_county.pt
        #- data/usa/symptom-survey/fb-survey_smoothed_hh_cmnty_cli-county.pt
        - data/usa/symptom-survey/fb-survey_smoothed_hh_cmnty_cli-county_state.pt
        #- data/usa/symptom-survey/fb-survey_smoothed_wcli-county.pt
        - data/usa/symptom-survey/fb-survey_smoothed_wcli-county_state.pt
        - data/usa/symptom-survey/doctor-visits_smoothed_adj_cli-county.pt
        # - data/usa/symptom-survey/doctor-visits_smoothed_adj_cli-county_state.pt
    ablation:
      -
        - data/usa/testing/total_features_county.pt
      - 
        - data/usa/fb/mobility_features_county_fb.pt
        - data/usa/fb/mobility_features_county_state_fb.pt
      - 
        - data/usa/google/mobility_features_county_google.pt
        - data/usa/google/mobility_features_county_state_google.pt
      -
        - data/usa/google/weather_features_county.pt
      -
        - data/usa/symptom-survey/fb-survey_smoothed_hh_cmnty_cli-county_state.pt
        - data/usa/symptom-survey/fb-survey_smoothed_wcli-county_state.pt
        - data/usa/symptom-survey/doctor-visits_smoothed_adj_cli-county.pt
    # graph: *fgraph
    activation: sigmoid
    no_cross_correlation: false
    decay: [lstm2_2]
    #window: [20, 25]
    window: [14, 21, 28]
    lr: [0.005]
    momentum: [0.9]
    dropout: [0.1]
    #weight_decay: [0.01, 0.1]
    weight_decay: [0.2, 0.3]
    # weight_decay: [0.3, 0.4, 0.5, 0.6]
    # niters: [40000]
    niters: [30000]
    granger: [0.5]
    # granger: [0]
    temporal: [100]
    #temporal: [0.1, 1]
    # eta: [0.1, 0.2]
    eta: [0.002, 0.02, 0.2]
    loss: nb
    t0: 0
    test_on: 30
naive:
  module: naive
  output: naive_model.npy
  data: data/usa/data_cases.csv
  train:
    days: *vdays
bar_lstm:
  output: bar_model.bin
  data: data/usa/data_cases.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 5
  train:
    n_models: 1
    fpop: *fpop
    # features: [[data/usa/county_features.pt]]
    time_features:
      -
        - data/usa/testing/total_features.pt
        - data/usa/testing/ratio_features.pt
        - data/usa/fb/mobility_features.pt
        - data/usa/google/mobility_features.pt
        - data/usa/google/weather_features.pt
        - data/usa/symptom-survey/features_state.pt
        - data/usa/symptom-survey/features_county.pt
    # graph: *fgraph
    activation: sigmoid
    no_cross_correlation: false
    decay: [lstm2_2]
    window: [15, 20, 25]
    lr: [0.001]
    momentum: [0.9]
    dropout: [0.1, 0.2]
    weight_decay: [0.1, 0.2]
    niters: [30000]
    granger: [0.5]
    temporal: [100, 1000]
    eta: [0.1, 0.2]
    loss: nb
    t0: 0
    test_on: *vdays
