region: us
population: &fpop covid19_spread/data/usa/population_county.csv
basegraph: &fgraph covid19_spread/data/usa/state_graph.pt
validation:
  days: &vdays 21
  output: validation.csv
test:
  days: 60
  output: validation.csv
forecast:
  output: forecast.csv
prediction_interval:
  output_mean: mean.csv
  output_std: std.csv
  intervals: [.95, 0.8, .5]
  nsamples: 5000
  batch_size: 10
sir:
  module: sir
  output: sir_model.npy
  data: covid19_spread/data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: 10
    recovery_days: 10
    distancing_reduction: 0.9
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
seir:
  module: seir
  output: seir_model.npy
  data: covid19_spread/data/usa/data_cases.csv
  train:
    fpop: *fpop
    window: [8, 10, 12, 14]
    recovery_days: [8, 10, 12, 14, 16]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    cases_to_infections_scale: [1.0, 2.0, 5.0, 10.0, 15.0, 20.0]
    # rate of progression
    sigma: [0.1, 0.15, 0.2, 0.3, 0.4]
sir_adaptive_beta:
  module: sir_adaptive_beta
  output: sir_adaptive_beta_model.npy
  data: covid19_spread/data/usa/data_cases.csv
  train:
    fpop: *fpop
    min_window: [5, 10, 20, 30]
    recovery_days: [10, 12, 14]
    distancing_reduction: [0.4, 0.6, 0.8, 0.9]
    # scale confirmed cases to get total infections
    cases_to_infections_scale: [1.0, 5.0, 10.0, 15.0]
    rolling_window: 5
    cap: 100.0
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
bar:
  output: bar_model.bin
  data: covid19_spread/data/usa/data_cases.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 3600
  #preprocess:
  #  smooth: 7
  train:
    n_models: 1
    fpop: covid19_spread/data/usa/population_county.csv
    time_features:
      -
        # - covid19_spread/data/usa/testing/ratio_features_county.pt
        - covid19_spread/data/usa/testing/total_features_county.pt
        - covid19_spread/data/usa/fb/mobility_features_county_fb.pt
        - covid19_spread/data/usa/fb/mobility_features_county_state_fb.pt
        - covid19_spread/data/usa/google/mobility_features_county_google.pt
        - covid19_spread/data/usa/google/mobility_features_county_state_google.pt
        - covid19_spread/data/usa/google/weather_features_county.pt
        #- covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_hh_cmnty_cli-county.pt
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_hh_cmnty_cli-county_state.pt
        #- covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_wcli-county.pt
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_wcli-county_state.pt
        - covid19_spread/data/usa/symptom_survey/doctor-visits_smoothed_adj_cli-county.pt
        # - covid19_spread/data/usa/symptom_survey/doctor-visits_smoothed_adj_cli-county_state.pt
    ablation:
      -
        - covid19_spread/data/usa/testing/total_features_county.pt
      - 
        - covid19_spread/data/usa/fb/mobility_features_county_fb.pt
        - covid19_spread/data/usa/fb/mobility_features_county_state_fb.pt
      - 
        - covid19_spread/data/usa/google/mobility_features_county_google.pt
        - covid19_spread/data/usa/google/mobility_features_county_state_google.pt
      -
        - covid19_spread/data/usa/google/weather_features_county.pt
      -
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_hh_cmnty_cli-county_state.pt
        - covid19_spread/data/usa/symptom_survey/fb-survey_smoothed_wcli-county_state.pt
        - covid19_spread/data/usa/symptom_survey/doctor-visits_smoothed_adj_cli-county.pt
    # graph: *fgraph
    activation: sigmoid
    no_cross_correlation: false
    decay: [lstm2_2]
    #window: [20, 25]
    window: [14, 21, 28]
    lr: [0.005]
    momentum: [0.9]
    dropout: [0.1]
    #weight_decay: [0.01, 0.1]
    weight_decay: [0.2, 0.3]
    # weight_decay: [0.3, 0.4, 0.5, 0.6]
    # niters: [40000]
    niters: [30000]
    granger: [0.5]
    # granger: [0]
    temporal: [100]
    #temporal: [0.1, 1]
    # eta: [0.1, 0.2]
    eta: [0.002, 0.02, 0.2]
    loss: nb
    t0: 0
    test_on: 30
naive:
  module: naive
  output: naive_model.npy
  data: covid19_spread/data/usa/data_cases.csv
  train:
    days: *vdays