region: us
population: &fpop data/usa/population.csv
basegraph: &fgraph data/usa/state_graph.pt
validation:
  days: &vdays 21
  output: validation-us.csv
forecast:
  output: forecast-us.csv
prediction_interval_:
  nsamples: 10
  output_mean: us_mean.csv
  output_std: us_std.csv
backfill:
  # LANL
  #- 2020-04-05
  #- 2020-04-08
  - 2020-04-12
  - 2020-04-15
  - 2020-04-19
  - 2020-04-22
  - 2020-04-26
  - 2020-04-29
  - 2020-05-03
  - 2020-05-06
  # IHME
  - 2020-05-01
  # GLEAM
  #- 2020-04-13
  #- 2020-04-20
  #- 2020-04-27
  #- 2020-05-04
  # MIT
  #- 2020-04-22
  #- 2020-04-27
  #- 2020-04-30
  #- 2020-05-04
metasir:
  data: data/usa/data.csv
  output: metasir_model.bin
  train:
    fpop: *fpop
    decay: rbf
    lr: 0.005
    weight_decay: 0
    niters: 10000
    method: euler
    loss: lsq
    t0: 10
    fit_on: -10
    test_on: *vdays
    adjoint: false    
ar:
  output: ar_model.bin
  data: data/usa/data_deaths.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  #preprocess:
  #  smooth: 5
  train:
    fpop: *fpop
    # features: data/usa/county_features.pt
    # time_features: data/usa/policy_features.pt
    # graph: *fgraph
    # decay: [latent2_1, latent4_1, latent8_1, latent16_1]
    decay: [latent2_1]
    window: [10, 15, 20, 25]
    lr: [0.001]
    momentum: [0.9]
    weight_decay: [0.1]
    # weight_decay: [0.01]
    niters: [20000]
    loss: nb
    t0: 10
    test_on: *vdays
sir:
  module: sir
  output: sir_model.npy
  data: data/usa/data.csv
  train:
    fpop: *fpop
    window: 10
    recovery_days: 10
    distancing_reduction: 0.9
    days: *vdays
    # number of days to keep for forecast
    keep: *vdays
dar:
  output: dar_model.bin
  data: data/usa/data_deaths.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  train:
    fpop: *fpop
    # features: data/usa/county_features.pt
    # time_features: data/usa/policy_features.pt
    # graph: *fgraph
    # decay: [latent2_1, latent4_1, latent8_1, latent16_1]
    decay: [latent16_1]
    window: [15, 10, 20, 25]
    lr: [0.001, 0.005]
    momentum: [0.99]
    weight_decay: [0.1, 0.01, 0]
    niters: [20000]
    loss: nb
    t0: 10
    test_on: *vdays
matrix:
  output: mc_model.bin
  fpop: *fpop
  data: data/usa/data.csv
  resources:
    gpus: 1
    cpus: 1
    memgb: 15
    timeout: 30
  train:
    decay: exp
    epochs: 40000
    bs: 100000 # 10000
    eps: [0.00001]
    lr: [0.0005]
    momentum: [0.99]
    weight_decay: [0.95]
    fit_on: [14]
    k_avg: [10]
    n_embedding: [250]
    seed: [1]
    t0: [0] #, 10] ######
    test_on: *vdays
