#+MACRO: NEWLINE @@latex:\\@@ @@html:<br>@@
#+Title: Transfer Entropy {{{NEWLINE}}} for High-Resolution COVID-19 Forecasting
#+Author: Maximilian Nickel, Matt Le, Mark Ibrahim, Levent Sagun, Timothee Lacroix {{{NEWLINE}}} Facebook AI Research
#+Publisher: Facebook AI Research

#+OPTIONS: toc:nil date:nil

#+LATEX_CLASS: tufte
#+LATEX_CLASS_OPTIONS: [nobib]
#+LATEX_HEADER: \usepackage[svgnames]{xcolor}
#+LATEX_HEADER: \usepackage{times}
#+LATEX_HEADER: \usepackage{hyperref}
#+LATEX_HEADER: \usepackage{url}


#+LATEX_HEADER: \makeatletter
#+LATEX_HEADER: \renewcommand{\maketitle}{%
#+LATEX_HEADER:   \newpage
#+LATEX_HEADER:   \global\@topnum\z@% prevent floats from being placed at the top of the page
#+LATEX_HEADER:   \begingroup
#+LATEX_HEADER:     \setlength{\parindent}{0pt}%
#+LATEX_HEADER:     \setlength{\parskip}{4pt}%
#+LATEX_HEADER:     {\Large\bf\@title}\par
#+LATEX_HEADER:     {\normalfont\normalsize\@author}\par
#+LATEX_HEADER:   \endgroup
#+LATEX_HEADER:   \thispagestyle{plain}% suppress the running head
#+LATEX_HEADER:   \tuftebreak% add some space before the text begins
#+LATEX_HEADER:   \@afterindentfalse\@afterheading% suppress indentation of the next paragraph
#+LATEX_HEADER: }

#+LATEX_HEADER: % Paragraph indentation and separation for normal text
#+LATEX_HEADER: \renewcommand{\@tufte@reset@par}{%
#+LATEX_HEADER:   \setlength{\RaggedRightParindent}{0pt}%
#+LATEX_HEADER:   \setlength{\JustifyingParindent}{0pt}%
#+LATEX_HEADER:   \setlength{\parindent}{0pt}%
#+LATEX_HEADER:   \setlength{\parskip}{0.5pc}%
#+LATEX_HEADER: }
#+LATEX_HEADER: \@tufte@reset@par
#+LATEX_HEADER: \makeatother
#+LATEX_HEADER: \fancyhead[RE,RO]{\newlinetospace{\color{gray}\plaintitle}\quad\thepage}

#+LATEX_HEADER: \usepackage{amsmath}
#+LATEX_HEADER: \usepackage{amssymb}
#+LATEX_HEADER: \usepackage{mathtools}
#+LATEX_HEADER: \usepackage{cleveref}
#+LATEX_HEADER: \usepackage{svg}
#+LATEX_HEADER: \usepackage{bm}
#+LATEX_HEADER: \usepackage{booktabs}
#+LATEX_HEADER: \usepackage{multirow}
#+LATEX_HEADER: \usepackage{grffile}
#+LATEX_HEADER: \usepackage{pgfplots}
#+LATEX_HEADER: \usepackage[caption=false]{subfig}
#+LATEX_HEADER: \usepackage{wrapfig}
#+LATEX_HEADER: \usepackage{microtype}

#+LATEX_HEADER: \pgfplotsset{compat=newest}
#+LATEX_HEADER: \usepackage{tikz}
#+LATEX_HEADER: \usetikzlibrary{positioning,quotes}

#+LATEX_HEADER: \usepackage[style=authoryear,backend=bibtex,natbib,maxcitenames=2,doi=false]{biblatex}
#+LATEX_HEADER: \addbibresource{./references.bib}

#+LATEX_HEADER: \hypersetup{
#+LATEX_HEADER:     colorlinks = true,
#+LATEX_HEADER:     allcolors = {DarkBlue}
#+LATEX_HEADER: }

#+LATEX_HEADER: \renewcommand{\vec}[1]{\bm{#1}}
#+LATEX_HEADER: \newcommand{\AR}{\text{AR}}
#+LATEX_HEADER: \newcommand{\Set}[1]{\mathcal{#1}}
#+LATEX_HEADER: \newcommand{\edge}{\sim}
#+LATEX_HEADER: \newcommand{\todo}[1]{{\color{red} #1}}

#+LATEX_HEADER: %\author{Maximilian Nickel\\Facebook AI Research\\New York, NY\\\texttt{maxn@fb.com}}

#+BEGIN_abstract
Modeling the spread of COVID-19 at a high spatial and temporal resolution has
become a key task in the public health response to the disease. This poses
unique challenges due to the novelty of the disease, its unknown
characteristics, and substantial but varying interventions to reduce its spread.
To alleviate this issue, we propose a new method to disentangle the properties
of the underlying contagion process from its concrete realizations across
spatial entities. Our aim is to separate region-specific aspects -- such as
demographics, enacted policies, and testing methods -- from disease-inherent
aspects that influence its spread. This allows us to train high-resolution
models which jointly model the spread and are able to borrow strength across
regions. In our experiments, we demonstrate that our approach achieves
state-of-the-art performance in predicting the spread of the COVID-19 and
improves the robustness of forecasts.
#+END_abstract

* Introduction
Forecasting the spread the of COVID-19 is an important task in the public
health response to the disease. It is not only important to understand the progress
of the disease, but is also central to efficiently allocate scarce resources such
as ventilators, personal protective equipment, and ICU beds.
For this purpose, it is especially important to forecast with a
high spatial and temporal resolution.

Simultaneously, forecasting COVID-19 poses unique challenges: Due to it's
novelty, many characteristics of the disease are still unknown. Moreover, there
exists little data about its spread, especially at the beginning of the
pandemic. Even several months after the initial outbreak there exists
substantially fewer data than for other infectious diseases like influenza and
measles which have been monitored for decades.

Due to its global nature, COVID0-19 occurs at the same time in regions with very
different properties that all affect its spread.qq This does not only include
different demographics and population densities, but also enacted policies,
adherence to those policies, mobility patterns, and geographic features such
as temperature. Moreover, testing and reporting can vary considerably across
regions what adds another source of variability and uncertainty.

* Method
We assume we have a set of time series which are different realizations of the
the same underlying contagion process. Let \(\Set{Y} = \{(y_i^1, \ldots,
y_i^T)\}_{i=1}^m\) denote the observed realizations where $i$ indexes locations and
where $T$ denotes the maximum observation time. Furthermore, let \(\lambda_i^t\)
denote the /force of infection/ at time \(t\) in location \(i\). We assume that
$\lambda_i^$ can be decomposed into a time-dependent component $\beta_i^t$ and a
time-independent component $\lambda$ such that \[ \lambda_i^t = \beta_i^t \lambda
\quad\text{where}\quad \beta_i^t \in [0, 1],\, \alpha > 0 \]

Hence, $\beta_i^t$ can be understood as a dampening factor of the underlying force
of infection that depends on time and location specific properties such as
policies, population density etc. We can then model the spread of COVID-19 using
a multivariate autoregressive model of the form \[ \AR(p): \quad y_i^{t+1} = \beta_i^t
\sum_{\ell=0}^{p-1} \sum_{j=1}^m \lambda_{ij}^\ell y_j^{t - \ell} \]

While some influencing factors for the evolution of $\beta_i^t$ are know (e.g.,
mobility), the full dynamics are still unknown. We will therefore regard $\beta_i^t$
as a latent variable which can depend on observed variables $\vec{x}_i^t$.

There exist many possible ways to model the evolution of $\beta_i^t$. In the
following, we will use a classic /Elman RNN/ where
\begin{align}
    \beta_i^t & = \sigma(\vec{w}^\top \vec{z}_t)
    & \vec{z}_t & = \psi(W_z\vec{h}_t + \vec{b}_z) \label{eq:rnn} \\
    && \vec{h}_t & = \psi(W_h\vec{x} + U\vec{h}_{t-1} + \vec{b}_h)\notag
\end{align}

Although an RNN as in ref:eq:rnn will provide enough capacity to model the
evolution of $\beta_i^t$ there is not enough data to estimate its parameters without
serious overfitting. For this

** AR

To simplify the discussion, we will assume in the following $p=1$. However, all
results generalize to $p > 1$.

\[
\frac{y_i^{t+1}}{\beta_t^i} - \sum_{j\neq k} \lambda_{ij}
y_i^{t} = \lambda_{ik} y_k^{t}
\]
*** Overdispersion

#+ATTR_LATEX: :float margin :width .8\columnwidth
file:img/overdispersion_states.png

#+ATTR_LATEX: :float margin :width \columnwidth
file:img/overdispersion_counties.png

\begin{equation*}
\Pr(Y = y) = \frac{\Gamma(y + \nu)}{y!\Gamma(\nu)}\left(\frac{\mu}{\mu +\nu}\right)^{y}\left(1 + \frac{\mu}{\nu}\right)^{-\nu}
\quad \mu > 0, \nu > 0
\end{equation*}

\begin{equation*}
    y^{t+1}_{i} \sim \text{NB}(\eta_i^{t}, \nu_i)
\end{equation*}

\begin{equation*}
    \min_\theta -\sum_{y} \log \Pr_\theta(Y = y)
\end{equation*}


** Transfer Entropy and Granger Causality
Transfer entropy measures the directed, time-asymmetric transfer of information
between two random processes $Y_i$ and $Y_j$. Intuitively, it captures the amount of
uncertainty reduced in future values of $Y_i$ by knowing the past values of $Y_j$ given
past values of Y. Formally, \[ T_{j \to i} = p_\theta(y^{t+1}_i, \Set{Y}^t) \log
\frac{p_\theta(y^{t+1} | \Set{Y}^t)}{p_\theta(y^{t+1} | \Set{Y}^t \textbackslash
y^t_j)} \]
** Regularzation

* Experiments
